### ISSUE TITLE
not showing up in Dalamud?

### ISSUE THREAD

**Issue by 4Head420** [awgil/ffxiv_bossmod#103]
I have added the experimental link in settings, but Boss Mod does not show up. 
What am I doing wrong? 
This is more so specifically for the minimap/raid encounter plugin.

**Comment by SitaNya** [comment]
My Boss Mod does not show up too.

**Comment by Makdag15** [comment]
I'm having the same issue.  How do I install this manually?

Here is a log if you care to see it.  The plugin isn't loading so it's not really showing anything.

[dalamud.log](https://github.com/awgil/ffxiv_bossmod/files/10582538/dalamud.log)

**Comment by Ants1988** [comment]
![image](https://user-images.githubusercontent.com/95916950/216759172-a64ee08e-9610-44ac-9e37-736745fcf8ad.png)

Did you remember to press the + before clicking the save button?

Boss Mod shows up fine for me so I'm unsure of what else could be causing your issue,

**Comment by Lusaca87** [comment]
Hello. 
Sorry to push this topic up!

For me, i cant find the plugin in Dalamud.
For the question if i have enabled the repository: yes i have, because i see the "better borderless window mode" plugin from the same repo.

i guess it maybe have some issues with "ApplicableVersion":  "2023.02.03.0000.0000", from the repo.
the other plugin dont have this line and is accessable.

if i try to use it with an another way (download and install it as dev plugin..) after adding it, it will be shown, but cant be loadet.

did i miss some way to get it work? 

best regards

**Comment by awgil** [comment]
Yes, that's because of the patch. Every patch randomizes network opcodes, so I have to update the plugin. That's why there is a version check - without it, people will run old plugin on new version and report weird bugs.

**Comment by Lusaca87** [comment]
No problem i wanted only to know if im right..

i know the weird problems with the op codes every single patch... so thank you for your answer.

**Comment by awgil** [comment]
I've just updated to the new version, should work now.
