### ISSUE TITLE
Auto rotation- Only BRD working

### ISSUE THREAD

**Issue by Kensei-Seiryuu** [awgil/ffxiv_bossmod#112]
Before I run and submit a debug report, I wanted to make sure if every class except BRD is not supposed to be working. I saw that only BRD was updated last week so I figured that all the other classes might be in the process of being updated.

**Comment by Ants1988** [comment]
The only class thats "supported" really is Warrior.

Everything else that exists in the code is either incomplete or only works for low level.

**Comment by Ants1988** [comment]
No clue

**Comment by Kensei-Seiryuu** [comment]
Does WAR auto rotation work with Maurader or only on the WAR? Maurader doesn't seem to work.

**Comment by awgil** [comment]
WAR and BRD currently work well, WHM is broken, some other classes work until L50 or so. There is no 'officially supported' list, since it's in 'permanent alpha' state, but you can check the code to see what's supported.

Marauder and similar don't work and probably never will, I see too little value in supporting these classes - unless I find a compelling reason to support them.
