### ISSUE TITLE
Bossmod visible in xbox windows dvr and obs

### ISSUE THREAD

**Issue by rrbailey89** [awgil/ffxiv_bossmod#115]
Is it possible to make it not show up when using game recording.

**Comment by Dubsys** [comment]
No.

**Comment by Nox13last** [comment]
No, but also ethically, no.
If you're going to cheat, you can't pretend in your recording that you're playing legitimately. That's the trade-off.

**Comment by Nox13last** [comment]
> I don't think ethics apply at all here, because the plugins themselves are already in violation of the ToS.
Correct reasoning, but incorrect conclusion IMO.
It's against the terms of service to use any plugin, mod, or "aftermarket" thing to change the way the game works. But I rely on plugins that make my cursor more visible against visual-noise so I get to play the game the same as everyone else. I relied on a Combat Parser once because my BLM output felt bad and I needed solid numbers to tell me that I was doing something wrong - I'm far more effective now. And as a combat mentor, I still use ACT to troubleshoot a player who asks me why pressing the buttons doesn't feel good.

It wouldn't be unethical to use Splatoon to highlight every Gathering Point nearby. But it would be to highlight every player using a Healer Role so I can decimate them in PvP.
It wouldn't be unethical to use Cammy to look at bullshit that the camera can't get to, but it was certainly unethical to use it to get a World First Clear a while ago.

As with everything else, "legal doesn't mean ethical", and the inverse is also true. For stuff like this, the ethics have to be kept squeaky-clean by the people who use it, or Squeenix will crack down on it, something *they* didn't feel like doing until someone used them to fuck with the competitive spirit of the game (the World First Clear).
So yes. Ethics **definitely** apply here, because the Dalamud scene depends on them.

**Comment by SirDK** [comment]
How can you talk about ethics when there is no generally accepted norm to use plugins? Most of the community do not use plugins. They have a norm of behavior - compliance with the ToS. What you're talking about is morality. Your personal idea of good and evil. 

> that will only lead to trouble for everyone else down the road

The people using the plugins have agreed to accept the risk and consequences.

**Comment by awgil** [comment]
I have no plans to accommodate for hiding the plugin windows specifically for streams, or in general make it more streaming-friendly (but neither I have any plans to actively prevent any workarounds - if something like putting a window on a second monitor works - good for you).

This is a personal project that I do for fun (since for me spending 10 hours reverse engineering how fights work, how to optimize rotations etc. is infinitely more interesting than spending 10 hours building muscle memory and learning visual cues), and I don't care about streaming like at all.

You are welcome to use this plugin however you see fit, if you do something stupid and it leads to you getting banned or getting booed by community for trying to mislead or whatever - that's on you.
