### ISSUE TITLE
Clarification - Cooldown Planner?

### ISSUE THREAD

**Issue by gamma-blocker** [awgil/ffxiv_bossmod#117]
Couple quick questions regarding cooldown planner:

1) Does it only work with "auto rotation" enabled?

2) Does it automatically activate the cooldowns for you, or does it provide a reminder to use the cooldown?

3) When some boss ability is occurring on the timeline with only a single ID, such as DSR Phase 2, triple tank buster (first TB in phase 2), does the ability's/action's "time" indicate the start of the ability, or the end of the ability?

**Comment by awgil** [comment]
Ok, so cooldown planner actually has two things - first, it feeds into autorotation (and that part obviously won't work with autorotation disabled), and second, there is the UI (controlled by "boss module window settings" -> "show window with cooldown plan timers" option) which shows time until next planned activation window, and colors timer differently depending whether you can safely use cooldown now and have it available until next window or not - and that part should work even if autorotation is disabled. That should ask your first two questions, with caveat that I didn't really test cooldown planner with autorotation disabled, so there could be bugs - if so, please tell me and I'll try to fix them.

Now, the UI itself is not especially good, I'd like to improve that someday, but I don't really like doing UI work and I don't have particularly great ideas in mind, so it's kinda sitting on a backburner for now.

All cooldown planner entries are defined relative to the previous state - so a single entry might be defined as "window starts 3.2 seconds after entering state X and is 4 seconds long". For casts, in most cases there are states both for cast-start and cast-end, however typically only cast-end has a defined name (though you can see all states in the plan editor window). There are some exceptions - for example, for many baited abilities where you actually care about bait rather than resolve the bait (cast start) state would have a name. In short, I don't have strict rules on whether or not states should be assigned a name or not - I typically assign state a name if it represents something important happening.

Specifically for DSR P2 TB, the "3x tankbuster cones" corresponds to the third tankbuster hit - if you look at the source (DSW2States.cs, look up where state is defined), you'll see that condition is NumCasts > 2. Hopefully that should be at least somewhat understandable even for a non-programmer, but yeah I agree that's a not particularly good UX.

All in all, I'd say the whole cooldown planner feature is quite unpolished - it works well for me, since I understand precisely how modules are written - but the UI is quite bad, both for planner and hints.
