### ISSUE TITLE
Problematic plugin behaviour after last updates

### ISSUE THREAD

**Issue by SirDK** [awgil/ffxiv_bossmod#127]
![image](https://user-images.githubusercontent.com/43450651/231466488-d3c40ab1-503c-4318-aeb1-5fb6a2a144ec.png)
I've encountered problems out of the blue. And all that is remarkable has happened recently - the plugins have been updated. Therefore, I had to disable one plugin after another to determine the source of the problems, which is shown in the screenshot as enabled options by default. Don't you think it should be turned off by default? And the user, at his own discretion, studies these options and turns them on if necessary. If you want to notify people about new features, you can do like other plugins - changelog popup. I believe it's the most trouble free solution.
v0.0.0.87

**Comment by awgil** [comment]
All these options *are* turned off by default. These are, however, not new options - they were previously part of autorotation settings - and recently were separated from it. Now, they were all turned off by default even while they were part of autorotation settings - so I assume they are turned on for you, because they were turned on before. I imagine you might not have noticed it before, if autorotation itself was disabled.

You could argue that I should have detected whether autorotation is disabled and forced settings to defaults in such case. You are also right that I could have written a changelog or made some other notification. However, I can't be arsed to do all that to be honest. This is not a plugin from the official repo, it's an obvious beta quality (versions are 0.0.0.something), so you are using it at your own risk - and should expect instability and/or breaking changes.
