### ISSUE TITLE
Bard AOE Autorotation

### ISSUE THREAD

**Issue by Stryker627** [awgil/ffxiv_bossmod#129]
Now i know that bard is not one of the completed autorotation classes, however the single target autorotation seems to work quite well.   that being said during the single target rotation it seems to cut off the wrong song short of its full duration, it ends Mages ballad early instead of armys paeon.  Do you have any plan to change that?

Also, the aoe rotation seems to use the exact same skills in the same order, IE no ladon's bite/rain of arrows.  is there a plan to fix the aoe rotation to utilize the proper skills?

**Comment by awgil** [comment]
BRD I actually consider to be 'complete'. So - definitely willing to fix any bad rotation decisions there.

I'm generally using information available on balance, and I don't see much guidance about AOE rotation there - so if you have any better info, please provide the link.

Song decisions are indeed made without taking aoe/non-aoe into account. What is the correct decision here?

> Also, the aoe rotation seems to use the exact same skills in the same order, IE no ladon's bite/rain of arrows. is there a plan to fix the aoe rotation to utilize the proper skills?

Don't understand what you mean here - it did use ladonsbite / rain of death correctly last time I've checked (assuming they hit 3+ enemies with current target, otherwise non-aoe rotation is preferred, according to balance). Are you saying that something is broken?

**Comment by Stryker627** [comment]
the song rotation itself is correct, however you have the rotation clipping off the last 15 seconds of Mage's Ballad,  it should instead clip off the last 15 seconds of Army's Paeon.  as for the Ladon's Bite and Rain of Death i was only testing the aoe rotation on a dummy so i did not know that your autorotation would cancel aoe and resort to single target if there were less than 3 targets available and i will happily retest.  Thank you for your response.

**Comment by Stryker627** [comment]
Apologies Awgil, after running a dungeon i can confirm you are correct and the aoe autorotation does use Ladon's Bite and Rain of Death if there is 3 or more targets.

**Comment by awgil** [comment]
Ok, so I now no longer end MB early by default if AOE rotation is used and rain of death can hit 3+ targets. It's not gonna be perfect, but should work in many cases - and who cares about slight inefficiencies on dungeon trash anyway.
