### ISSUE TITLE
Prevent movement while casting setting causes stutters on characters movement

### ISSUE THREAD

**Issue by XeonTimes747** [awgil/ffxiv_bossmod#131]
the setting "Prevent movement while casting" causes the character to stutter in place momentarily while moving when using certain skills, most notably instant spell casts like for example on summoner(during garuda or titan phase using ruin makes it happen for example)

**Comment by awgil** [comment]
Interesting - I don't know anything about SMN - are these spells by chance 'conditionally instant' (e.g. in some cases instant, in some casted)? Could you give any example and explain it in detail - proper full spell name, conditions, etc.

Current logic is extremely simple - if next spell to be casted has non-zero cast time, it locks the movement when gcd is less than 100ms.

**Comment by XeonTimes747** [comment]
" are these spells by chance 'conditionally instant' ", yep you could say that the main one is a skill called ruin which goes from being cast normally to insta cast during garuda and titan summon phase, during which time these stutters in movement occur each time they are cast, the only time they don't occur is when you wait for a gcd to fully come up, then use it, instead of queuing it up.

**Comment by awgil** [comment]
Could you please do the following:
1. Open debug menu ("/vbm d" in chat) -> Actions
2. Hover over 'ruin' when it's a normal cast - and tell me what's written there (i'm really only interested in "Hover action: " and "Adjusted cast:" lines).
3. Use garuda summon or whatever is needed to turn it into instant cast, then hover over 'ruin' again and tell me what's written in these fields now.

**Comment by awgil** [comment]
Ok, I have some idea what might be causing it, but I'm not 100% sure, and since I don't have any class with similar mechanics, I'll need help debugging. So could you please do the following test:
1. Open debug UI (/vbm d) -> Action manager ex menu and look at the Queue line
2. Summon garuda, so that you have instant ruin proc
3. Cast something else that doesn't break the proc and then immediately spam ruin - goal is to press the button during animation lock (or cooldown), so that ruin is queued (spells are queued by the game if pressed while on cooldown/anim lock and less than 500ms remains).
4. You should see queue become active for a moment - see what action is queued - it would be either normal ruin (3579) or emerald ruin (25819) - and tell me the result.

It might be worth recording a short video clip to better see what's happening.

**Comment by awgil** [comment]
Should be fixed in the new version, please verify and tell me the results!

**Comment by XeonTimes747** [comment]
yep tested, no issues now, thanks!
