### ISSUE TITLE
Question for the plugin devs: How to contribute?

### ISSUE THREAD

**Issue by farchord** [awgil/ffxiv_bossmod#143]
Hello, I'm a c# coder (In my free time) and I play FFXIV in Linux. I've been using this plugin for a while, and I love it. It helps a lot.

I wanted to ask if you were looking for collaborators, and if so, how I would go about helping. I've been browsing the code for the repo a little bit, but I don't know if you use special tools to "capture" a fight, or if you simply need testers. I'd be happy to help.

**Comment by awgil** [comment]
Re. capturing - the pipeline is really simple - dump a log (config -> General -> Dump world state events), then run UIDev standalone executable, open it there and analyze. Typically I just enable that every time before entering instance, and store single log per lockout.

That's one of the process I'd like to improve:
# Create dedicated window (hidden by default) with start/stop recording actions.
# Move the whole replay framework from UIDev to main project, allowing using it in-game (and add some UI to e.g. open any log, open last written log, open cooldown planner with last pull, and so on).
# Allow adding custom messages with timestamp to the replays (e.g. to mark last pull as interesting for later analysis).
# Reduce log size (instead of writing text lines, use some binary format + compression), since now I have tens of gigs of logs already...

As for contributions - just make a PR if you wanna improve something (if it's a larger thing, might be worth discussing first).

**Comment by awgil** [comment]
I just run from VS directly (set as startup project and hit F5). I always do that in debug mode, it needs some slight tweaking to make it run in Release. Game doesn't have to be open.

See whether there are any messages in VS console.

**Comment by cptjabberwock** [comment]
Hello, I really like this and as such would like to contribute. However, I'm not good at anything else than recording the battle with a log and then posting it somewhere here for someone knowledgable to do the graph and timeline

I mostly like it for Foray content like Eureka's Baldesion Arsenal (maybe outdoor NM ?) and Bozja

There are some CE and DRS

How would I go about recording CE (for those that aren't in the list) and DRn, Castrum and Dalriada
Can I make a dump file for each encounter individually ? and where would they be stored ?

**Comment by ViennaGuy** [comment]
How might one contribute towards autorotations?

**Comment by Stryker627** [comment]
> How might one contribute towards autorotations?

this is something i would also like to know

**Comment by awgil** [comment]
Outdated. Not an issue.
