### ISSUE TITLE
Sticky auto rotation breaking when using actions that require other friendly targets

### ISSUE THREAD

**Issue by Dedoooo** [awgil/ffxiv_bossmod#145]
When using actions that require another target such as Nascent Flash the auto combo stops for a short amount of time.

Cheers for this plugin! I love it.

**Comment by awgil** [comment]
Couldn't reproduce - how exactly do you use it? FWIW I use 'smart-targeting' for things like nascent flash or shirk (it casts at friendly mouseover or at co-tank). Do you actually switch targets? In such case I imagine autorotation would stop until you target enemy again (because that's how it works, at least for now - it always attacks main target).

**Comment by awgil** [comment]
You can already toggle any config by command, see /vbm cfg
