### ISSUE TITLE
Make options toggleable

### ISSUE THREAD

**Issue by abranon** [awgil/ffxiv_bossmod#16]
Rewording for clarity

**Comment by awgil** [comment]
Can you clarify what exactly do you propose?

Currently option is toggleable via config (and, since it's disabled by default, I assume that you've found it and enabled it - and thus are asking for some other toggle).

**Comment by abranon** [comment]
Gotcha, I wasn't aware the mouse movement negated the option but I do think that a toggle option might still be beneficial, adding the toggle command to a slash command makes it easy to add it to your in-game macros and essentially make a button that lets you cancel the movement locks until you turn it back on.

Another option might be a double-tap to move but I'm not sure how well that would work in application.

**Comment by abranon** [comment]
Also something else I've noticed playing WHM is that ticking on the smart queue system and using Asylum, Liturgy or Aquaveil (not sure if more but can check) ignores the input and behaves as if I'm casting glare.
So what I click is 
Glare > Dia > Glare > POM > Glare > Asylum 
What instead happens is
Glare > Dia > Glare > POM > Glare > Glare > Glare > Dia > Asylum

**Comment by awgil** [comment]
Slash command should be simple to implement.

Re. ogcds not casting - current logic only considers casting ogcds if it won't delay next gcd. Under POM this window is quite small (~0.5s, less if you have lag) - if you don't hit your glare button in this window, ogcd won't be cast (since that would delay gcds). I think I need to add some option that allows delaying GCDs by some small configurable amount for WHM (and in future for other healers and/or casters?), since getting that ogcd off is really much more important for a healer than maximizing gcd uptime...

**Comment by awgil** [comment]
Added console commands to toggle various config options. Try "/vbm cfg" (it will show help messages, from there it should be straightforward).

**Comment by abranon** [comment]
Sorry for the late reply, I got to mess with it a bit this weekend to see how it works and I think I'd need an example or list of what are valid responses. I tried true and false which don't give any indication of it toggling but also doesn't say it's failed; and on/off which gives me a an error that its not valid so that's good

**Comment by awgil** [comment]
For example: `/vbm cfg Autorotation PreventMov false`

**Comment by abranon** [comment]
Works exactly how I expected, thanks!

**Comment by awgil** [comment]
Note to self: not closing this issue, since there's still unresolved feature request here about tight ogcd windows under things like POM
