### ISSUE TITLE
Separate Autorotation + Cooldown mapping from BossMod Addon + Move map

### ISSUE THREAD

**Issue by bricksquad10171017** [awgil/ffxiv_bossmod#19]
Would it be possible to split the auto-rotation and cooldown mapping components from the rest of the addon? 

Also is it possible to get a setting to manipulate the relative position of the radar map within the box it's rendered within? Setting it to 1.2+ scale makes it clip a bit within the box, being able to manipulate or have a central anchor with xy coordinates to move/rejig the position would be great.

**Comment by awgil** [comment]
> Would it be possible to split the auto-rotation and cooldown mapping components from the rest of the addon?

This would be nice, however I have no idea how to do that. The problem is that autorotation and cooldown planner use information from bossmods, and I don't know how to make two independent dalamud plugins interact.

> Also is it possible to get a setting to manipulate the relative position of the radar map within the box it's rendered within? Setting it to 1.2+ scale makes it clip a bit within the box, being able to manipulate or have a central anchor with xy coordinates to move/rejig the position would be great.

Can you show some screenshot with this clipping problem? I just tried extreme scales (3+), and if I make window big enough by resizing, it works fine for me.

That said, I'll see what I can do with manual center x/y offsets...
