### ISSUE TITLE
How to Generate Definition Files for New Classes?

### ISSUE THREAD

**Issue by MrGuffels** [awgil/ffxiv_bossmod#192]
Hey, Figure this is the best way to reach out but feel free to direct me somewhere else.

Looking to take a stab at Dancer Autorotation (Kinda bored, got a week of time off work lol) or at least get the basics set up.

Is there some kind of script you are using to generate the Definition files?

**Comment by awgil** [comment]
Hi - so that's a somewhat complicated process. The first step is indeed generating the definitions, there's a special menu in debug menu (/vbm d) to assist with that (try different context menus). Then you would write the Rotation part (which is essentially definition of a rotation in vacuum - without any actors etc), then finally Actions part (which builds state needed for rotation based on world state).

**Comment by MrGuffels** [comment]
It's a lot more manual labor on the definition files than I expected for how many have been worked on. The comments were the most impressive part. Figured it had to be an auto formatted API call. Almost done with definitions. Thanks for the starting point.
