### ISSUE TITLE
about uidev

### ISSUE THREAD

**Issue by tssailzz8** [awgil/ffxiv_bossmod#3]
how can i use zhe uidev

**Comment by tssailzz8** [comment]
and in Server_ActorControlCategory, what is means "from dissector",can you tell where it from

**Comment by awgil** [comment]
Re. uidev - just open solution in visual studio, build debug config and run... You might need to copy some imgui dll from datamud install dir to output, I remember there were some problems with that, but don't remember the details.

Re "from dissector" comments - these are taken from https://github.com/zhyupe/FFXIV-Packet-Dissector (there's a comment somewhere is Protocol.cs about that iirc). This project has a lot of packet structures and field values, but seems to be no longer actively maintained, so some information is outdated.

**Comment by tssailzz8** [comment]
![image](https://user-images.githubusercontent.com/52206101/154905286-9e8ada17-166c-42b9-bae9-54bb19a5cccf.png)
i use it and build this,i open the UIDev.exe then it open a window and close soon,i do not what problems

**Comment by awgil** [comment]
If you run it from Visual Studio (just press F5), it should write what exactly is the problem - please try that and tell me details...

**Comment by tssailzz8** [comment]
![image](https://user-images.githubusercontent.com/52206101/154917962-efd5a449-7210-4b3c-8a42-53ff0c6bc5ff.png)
System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'cimgui' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
  Source=<无法计算异常源>
  StackTrace:
<无法计算异常堆栈跟踪>

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]
    UIDev.UIBootstrap.Inititalize(UIDev.IPluginUIMock) (位于 UIBootstrap.cs 中)
    UIDev.UITest.Main(string[]) (位于 UITest.cs 中)

**Comment by awgil** [comment]
Yeah, that's what I've written about - you need to find cimgui.dll in XIVLauncher installation directory (C:\Users\username\AppData\Roaming\XIVLauncher\... for me) and copy it manually to output directory where UITest.exe is located.

Or just wait a bit, i'll try to fix project to do that automatically on build :)

**Comment by tssailzz8** [comment]
i only find the ImGui.NET.dll and ImGuiScene.dll not find cimgui.dll ,i will wait you to fix it

**Comment by SashaFFXIV** [comment]
> i only find the ImGui.NET.dll and ImGuiScene.dll not find cimgui.dll ,i will wait you to fix it

C:\Users\USERNAME\AppData\Roaming\XIVLauncher\addon\Hooks\6.3.0.4\runtimes\win-x64\native

It's in there.

**Comment by tssailzz8** [comment]
ok，it fine. and i am not good at Engish,i see the timeline is all English.can change the LuminaGameData language？

**Comment by awgil** [comment]
About language - in-game, addon uses Lumina instance provided by dalamud, I'm not sure but I expect it to use current in-game language by default. In UITest, Lumina is initialized manually using hardcoded path and default language - it can be customized as needed, see UITest.Initialize - ideally it would either detect path/language automatically or provide some ui to customize, but since UITest is really a development tool, I didn't bother.

That said, changing Lumina language won't change that much in UITest anyway - for example, boss modules use hardcoded names for states. Theoretically I could take ability names from Lumina instead, but many states use custom names (for example, they call tankbusters or aoes simply "tankbuster" or "aoe", rather than using boss-specific names that I never bother to remember :)), and not all states correspond to boss casts anyway.

Now, about initial problem with cimgui.dll - I actually have no idea how that is supposed to work by design; I've used "dalamud sample" project as a template, it uses "$(appdata)\XIVLauncher\addon\Hooks\dev\" as DalamudLibPath, but this "dev" directory doesn't contain cimgui.dll; directory with concrete version does contain it, but I don't think it's a good idea to hardcode concrete dalamud versions into buildsystem of my plugin.

**Comment by tssailzz8** [comment]
oh,i think maybe support other language,like SimpleTweaksPlugin.

**Comment by tssailzz8** [comment]
and in this 
![image](https://user-images.githubusercontent.com/52206101/155045412-317d11af-e7d4-4dd8-b20e-cec4c6dfe04e.png)
it not tell me close  or away

**Comment by SashaFFXIV** [comment]
Oh yea I kept forgetting to make an issue for that. The Left/Right-In/Out-Fire/Light mechanic during Shining Cells does not display the In/Out mechanic in the Boss Module.

**Comment by tssailzz8** [comment]
in Server_ActorControlCategory==UnkVisControl can look it

**Comment by awgil** [comment]
> oh,i think maybe support other language,like SimpleTweaksPlugin.

I don't really plan full localization, at least for now - that would make changing things significantly more difficult for me, and since plugin is currently in very early alpha stage, it changes a lot. If you wish, you can fork the plugin and translate things manually - you would have to merge with master manually, however - it's up to you whether you think it is worth the effort...

> Oh yea I kept forgetting to make an issue for that. The Left/Right-In/Out-Fire/Light mechanic during Shining Cells does not display the In/Out mechanic in the Boss Module.

Huh? You mean "aetherflails" mechanic? It should be working - I did break it recently, but fixed it afterwards... Currently, looking at logs from last week, I see this:
![Untitled](https://user-images.githubusercontent.com/20607474/155091878-6298ed5a-5593-412d-b827-cf402fcb1f8b.png)

If it really doesn't work with latest version, please record the logs (config -> general -> dump world state events) from the fight and send me for investigation (probably open a new issue for that though)... The detection logic is not trivial, but not particularly complex either (for light/fire, it checks the parameter of a hidden boss buff; for in/out/side it uses a combination of action IDs and spawned actor IDs).

**Comment by awgil** [comment]
Ok, fixed original problem about automatic deployment of imgui dll for UITest (apperently there was unmerged PR to sample plugin that resolves this).

For remaining problems, please open new issues :)
