### ISSUE TITLE
[Feature Request] Minimap update with Role colors

### ISSUE THREAD

**Issue by KhaozFrost** [awgil/ffxiv_bossmod#48]
So I was thinking on the minimap if we changed the bosses color to something else (Gray/white? idk)
and then changed the party members colors based on role
Tank = Light Blue
Healer = Light Green
Melee = Light Red
Ranged = Orange
Caster = Light Purple

Then we could see in reference about where people are at by role.

**Comment by awgil** [comment]
That's not hard to implement (say, as an option).

However, current design color-codes players somewhat based on their 'importance' to current mechanic (e.g. player that is handling dangerous mechanic that you should stay away from is typically yellow, player that is being clipped by mechanic PC is handling is a bit lighter shade of gray). This isn't particularly consistent, and I'm not 100% sure how useful it is - in any case, with the proposed feature that information would be lost. Or, I guess, you could use this as 'overrides' and fallback to role colors (instead of current gray) for 'irrelevant' players - but at that point wouldn't it create too much visual noise to be useful?..

BTW why do you even care about people's roles on radar? Per my original intent, radar should help you (the player) resolve the mechanics, so other's role shouldn't matter that much (unless you have mechanics where e.g. tanks do specific stuff - but that is/should be covered by what I've described above) - am I wrong in that assumption?

**Comment by Capritle** [comment]
Adding on to this, I think while it certainly would not be useful from the normal use case, and therefor is only valuable as an option, I _do_ see potential use. For myself at least I am a raid lead for my static, and generally do callouts and such. Seeing colors of my party members in an organized environment could allow for seeing who's out of position for role-based mechanics. This also comes into benefit if a group is utilizing role based solutions that aren't the 'norm', but I also understand that the radar isn't meant to cater to individual's strats for a particular group.

**Comment by KhaozFrost** [comment]
> Adding on to this, I think while it certainly would not be useful from the normal use case, and therefor is only valuable as an option, I _do_ see potential use. For myself at least I am a raid lead for my static, and generally do callouts and such. Seeing colors of my party members in an organized environment could allow for seeing who's out of position for role-based mechanics. This also comes into benefit if a group is utilizing role based solutions that aren't the 'norm', but I also understand that the radar isn't meant to cater to individual's strats for a particular group.

yeah I didn't know about the whole " (e.g. player that is handling dangerous mechanic that you should stay away from is typically yellow, player that is being clipped by mechanic PC is handling is a bit lighter shade of gray)" I mainly looked at the circles and such for 'stay away from user' and was looking at it from a Raid lead perspective to see without much effort who perhaps was in the wrong zone is all. but i can see whats being said.

**Comment by KhaozFrost** [comment]
I also don't notice any color changes on the minimap for player icons specifically. The player arrows show gray the boss shows red and yours shows green.

**Comment by awgil** [comment]
Outdated. No plans to implement, per comment above, player's color is currently tied to relevance to active mechanics. Might implement as an option if there's sufficient demand.
