### ISSUE TITLE
No map?

### ISSUE THREAD

**Issue by mscho1o1** [awgil/ffxiv_bossmod#59]
Wondering when P8S phases 1 and 2 will come out? There is no map for those fights...

**Comment by Rueby** [comment]
Wondering the same thing too!

**Comment by Tipsoop** [comment]
There's no P8S? At least phase 1.

**Comment by bostonpsycho** [comment]
No Map, Also if it's possible to include the Japanese rotation as well in the map. 
Stormscrown, p1-8 if possible and further going updates would be amazing

**Comment by awgil** [comment]
P8S phase 1 is now supported, P8S phase 2 not yet.

Don't understand last question about 'japanese rotation'.

**Comment by bostonpsycho** [comment]
Amazing, I was hoping you could throw the boss map for eventually all the
bosses from extreme/savage. Obviously I know it would take some time and
effort but this is probably the best plug in I've seen.

The Japanese rotation is because stormscrown extreme (Japan server) is
slightly different than the (north American and EU) servers. I'm not very
smart on programming which is why I thought I'd bring it in discussion.

I play in Japan which is why I was asking for that and I'm sure lots of
people would wide would love and support your plug-in!

Keep up the great work! I've been impressed with everything you are aiming
for this to become!
