### ISSUE TITLE
How to use in chinese server

### ISSUE THREAD

**Issue by NTnarasha** [awgil/ffxiv_bossmod#60]
game version is 6.15. bossmod is 0.60. it shows "fail to load". when i chose the  other people's bossmod it works. i don't kown why the version in github fail to load but the other guys can work. here is the other guys document
[bossmod.zip](https://github.com/awgil/ffxiv_bossmod/files/9763927/bossmod.zip)

**Comment by awgil** [comment]
Ok, I have no idea what's the deal with CN servers (I know that they have different network opcodes, do they also have different game versions?) - and because of that I don't really support that. I guess best way would be to take last commit before 'updated to version N+1' in the repo, update opcodes manually to whatever CN uses, and build locally - but I can't really help with that, sorry...
